use super::*;

pub struct IcosahedronModel {
	pub vertices: VertexBuffer,
	pub vertices_len: u32,
	pub indices: IndexBuffer,
	pub indices_len: u32,
}

pub struct IcosahedronFlatModel {
	pub vertices: VertexBuffer,
	pub vertices_len: u32,
}

impl IcosahedronModel {
	pub fn create(g: &mut Graphics) -> IcosahedronModel {
		let vertices = g.vertex_buffer(None, &VERTICES, BufferUsage::Static);
		let vertices_len = VERTICES.len() as u32;
		let indices = g.index_buffer(None, &INDICES, vertices_len as u8, BufferUsage::Static);
		let indices_len = INDICES.len() as u32;

		IcosahedronModel { vertices, vertices_len, indices, indices_len }
	}
	pub fn draw(&self, g: &mut Graphics, shader: Shader, uniforms: &[&dyn UniformVisitor]) {
		g.draw_indexed(&DrawIndexedArgs {
			scissor: None,
			blend_mode: BlendMode::Solid,
			depth_test: Some(DepthTest::LessEqual),
			cull_mode: Some(CullMode::CW),
			mask: DrawMask::ALL,
			prim_type: PrimType::Triangles,
			shader,
			uniforms,
			vertices: &[DrawVertexBuffer {
				buffer: self.vertices,
				divisor: VertexDivisor::PerVertex,
			}],
			indices: self.indices,
			index_start: 0,
			index_end: self.indices_len,
			instances: -1,
		});
	}
}

impl IcosahedronFlatModel {
	pub fn create(g: &mut Graphics) -> IcosahedronFlatModel {
		let vertices = g.vertex_buffer(None, &FLAT_VERTICES, BufferUsage::Static);
		let vertices_len = FLAT_VERTICES.len() as u32;
		IcosahedronFlatModel { vertices, vertices_len }
	}
	pub fn draw(&self, g: &mut Graphics, shader: Shader, uniforms: &[&dyn UniformVisitor]) {
		g.draw(&DrawArgs {
			scissor: None,
			blend_mode: BlendMode::Solid,
			depth_test: Some(DepthTest::LessEqual),
			cull_mode: Some(CullMode::CW),
			mask: DrawMask::ALL,
			prim_type: PrimType::Triangles,
			shader,
			uniforms,
			vertices: &[DrawVertexBuffer {
				buffer: self.vertices,
				divisor: VertexDivisor::PerVertex,
			}],
			vertex_start: 0,
			vertex_end: self.vertices_len,
			instances: -1,
		});
	}
}

// Unit-radius icosahedron centered at origin.
// Generated by the ignored test in src/d3/icosahedron/tests.rs.

crate::include_bin!(pub(crate) VERTICES: [TexturedVertexN] = "icosahedron/vertices.bin");
crate::include_bin!(pub(crate) INDICES: [u8] = "icosahedron/indices.bin");
crate::include_bin!(pub(crate) FLAT_VERTICES: [TexturedVertexN] = "icosahedron/flat_vertices.bin");

#[cfg(test)]
mod tests;
